name: bulls_eye
author: SoftHai <softhai@gmx.de>
version: 0.2.0-alpha
homepage: https://github.com/SoftHai/Bulls-Eye
description: Bulls Eye is an Dart-IO Extension to build up an WebServer (like node.js and Express)
documentation: https://github.com/SoftHai/Bulls-Eye
dev_dependencies:
  spec_dart: any
  unittest: '>=0.9.0 <2.0.0'
