name: BullsEye
version: 0.0.1-alpha
author: SoftHai <softhai@gmx.de>
description: Bulls Eye is an Dart-IO Extension to build up an WebServer (like node.js and Express)
homepage: https://github.com/SoftHai/Bulls-Eye
documentation: https://github.com/SoftHai/Bulls-Eye
dev_dependencies:
  unittest: '>=0.9.0 <2.0.0'
